@startuml
class Boiler{
    + {static} devtype: string 
    + {static} energy: string
    + name: string 
    + iPort: Port[1]
    + oPort: Port[1]
    + portdict: dict
    + heatAdded: float  
    + QAdded: float 
    + {static} __init__(dictDev：dict)
    + state()
    + balance()
    + equation_rows()
    + energy_fdot()
    + calmdot(totalmass:float)
    + sm_energy()
    +__str__(): str
}
note right of Boiler::__init__
    {"name": "BO",
     "devtype": "BOILER", 
     "iPort": {},
     "oPort": {}}
end note

@enduml