@startuml
class Device{
    + {static} devtype: string 
    + {static} energy: string
    + name: string 
    + iPort*: Port
    + oPort*: Port
    + value*: float  
    + {static} __init__(dictDev：dict)
    + state()
    + balance()
    + equation_rows()
    + energy_fdot()
    + calmdot(totalmass:float)
    + sm_energy()
    +__str__(): str
}
note left of Device::balance
    sequential-modular
end note
note left of Device::equation_rows
    equation-oriented 
end note
note left of Device::energy_fdot
    equation-oriented 
end note
note right of Device::__init__
    {"name": "*",
     "devtype": "*", 
     "iPort*": {},
     "oPort*": {},
      "Value*": * }
end note
Device "1" *-- "2..*" Port 

@enduml